openapi: 3.0.0
info:
  title: HR
  version: 1.0.0
paths:
  /hr:
    post:
      tags: 
        - hr
      summary: Отправка кандидата в сервис HR
      operationId: sendUser
      security:
        - Authorization: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
              properties:
                userName:
                 type: string
                 description: Логин пользователя     
      responses:
        '200':
          description: Пользователь отправлен в HR
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Идентификатор отправленного пользователя
        '400':
          description: Неверный запрос
        '401':
          description: Неавторизован
        '500':
          description: Внутренняя ошибка сервера